#!/usr/bin/env python3
array = [2, 3, 4, 5, 6, 7, 2, 8, 8, 10, 12]
inc_array = [int(n) + 2 for n in array]
new_array = list(set(inc_array))
print(new_array)




#newlist =[]
#for duplicates in array:
    #if duplicates not in newlist:
        #newlist.append(duplicates)
#print(newlist)